version: '3.7'
services:
  ngen-frontend-new:
    image: ngen-frontend-new:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=/metrics
      - REACT_APP_API_SERVER=http://localhost:8000/api/
      - CHOKIDAR_USEPOLLING=true
      