# pull official base image
FROM node:18-alpine AS ngen-frontend

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH=/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN npm install --verbose
# # RUN npm install --global yarn --verbose
# # upgrade yarn
# RUN npm install --global yarn --force -g corepack
# RUN yarn install
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

# add app
COPY . ./

# Expose port
EXPOSE 3000

# start app
CMD ["npm", "run","start"]
