FROM python:3.11.10-alpine3.20 AS ngen-django

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apk add gettext libmagic gcc musl-dev python3-dev

COPY . /code/

# Add version information
ARG APP_VERSION_TAG
ARG APP_COMMIT
ARG APP_BRANCH
ENV APP_VERSION_TAG=$APP_VERSION_TAG
ENV APP_COMMIT=$APP_COMMIT
ENV APP_BRANCH=$APP_BRANCH
ENV APP_BUILD_FILE="dev"
RUN echo "{\"tag\": \"$APP_VERSION_TAG\", \"commit\": \"$APP_COMMIT\", \"branch\": \"$APP_BRANCH\", \"build_file\": \"$APP_BUILD_FILE\"}" > /code/version.json

# Must be built from the project root directory
RUN pip install -r requirements.txt
