# Generated by Django 3.2.5 on 2021-12-09 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0001_squashed_0037_alter_priority_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttype',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='incidenttype',
            name='is_classification',
        ),
        migrations.RenameField(
            model_name='incidenttype',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='incidenttype',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.incidenttype'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='active',
            field=models.BooleanField(),
        ),
    ]
