# Generated by Django 4.1.10 on 2024-04-19 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
