# Generated by Django 3.2.5 on 2021-09-01 19:29

from django.db import migrations, models
import django_dnf.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='domain',
            field=django_dnf.fields.DomainNameField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='domain',
            field=django_dnf.fields.DomainNameField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
