# Generated by Django 4.0.8 on 2023-03-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkentity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
