# Generated by Django 4.1.10 on 2024-04-28 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0002_communicationchannel_communicationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CommunicationChannelContactRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('communication_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channel_contact_relations', to='ngen.communicationchannel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channel_contact_relations', to='ngen.contact')),
            ],
            options={
                'unique_together': {('communication_channel', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='additional_contacts',
            field=models.ManyToManyField(through='ngen.CommunicationChannelContactRelation', to='ngen.contact'),
        ),
    ]
