# Generated by Django 3.2.5 on 2021-10-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0002_auto_20210901_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='networkadmin',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='networkadmin',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='networkentity',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='networkentity',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='host',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='network',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='networkadmin',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='networkentity',
            name='deletedat',
        ),
        migrations.AddField(
            model_name='host',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkadmin',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkentity',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
