# Generated by Django 4.1.10 on 2024-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0003_alter_case_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationchannel',
            name='communication_types',
            field=models.ManyToManyField(through='ngen.CommunicationChannelTypeRelation', to='ngen.communicationtype'),
        ),
    ]
