# Generated by Django 4.1.10 on 2024-05-10 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngen", "0003_evidence_original_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactrelation",
            name="auto_created",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this relation was created automatically and may will be removed automatically when the related object is modified.",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
