# Generated by Django 3.2.5 on 2021-10-23 00:53

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0004_auto_20211020_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='ip_end_address',
        ),
        migrations.RemoveField(
            model_name='network',
            name='ip_start_address',
        ),
        migrations.AddField(
            model_name='host',
            name='cidr',
            field=netfields.fields.CidrAddressField(blank=True, max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='cidr',
            field=netfields.fields.CidrAddressField(blank=True, max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=netfields.fields.InetAddressField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=netfields.fields.InetAddressField(blank=True, max_length=39, null=True),
        ),
    ]
