# Generated by Django 4.1.10 on 2024-05-12 19:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0004_communicationchannel_communication_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('root_message_id', models.CharField(max_length=255)),
                ('parent_message_id', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'email_message',
            },
        ),
    ]
