# Generated by Django 3.2.5 on 2021-10-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0005_auto_20211023_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
