# Generated by Django 4.1.10 on 2024-08-01 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0005_event_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'taxonomy_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='initial_taxonomy_slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='alias_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ngen.feed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='network',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ngen.network'),
        ),
        migrations.AlterField(
            model_name='event',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='type',
            field=models.CharField(choices=[('vulnerability', 'Vulnerability'), ('incident', 'Incident'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomies', to='ngen.taxonomygroup'),
        ),
    ]
