# Generated by Django 3.2.5 on 2021-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0005_alter_incidenttype_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taxonomypredicate',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyvalue',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
