# Generated by Django 4.1.10 on 2024-07-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0005_event_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='is_alias',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='network',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ngen.network'),
        ),
    ]
