# Generated by Django 3.2.5 on 2021-12-09 22:28

from django.db import migrations


def copy_taxonomy_predicates_to_types(apps, schema_editor):
    taxonomy_predicates = apps.get_model('ngen', 'TaxonomyPredicate')
    incident_types = apps.get_model('ngen', 'IncidentType')

    for taxonomy_predicate in taxonomy_predicates.objects.all():
        incident_types.objects.create(name=taxonomy_predicate.expanded,
                                      description=taxonomy_predicate.description,
                                      slug=taxonomy_predicate.slug,
                                      )


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0006_auto_20211209_2320'),
    ]

    operations = [
        migrations.RunPython(
            code=copy_taxonomy_predicates_to_types,
        ),
    ]
