# Generated by Django 3.2.5 on 2021-10-20 22:32

from django.db import migrations


def set_people(apps, schema_editor):
    networks = apps.get_model('ngen', 'Network')
    for row in networks.objects.all():
        if row.ip:
            row.cidr = row.ip.ip.exploded + '/' + str(row.ip_mask)
            row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0006_auto_20211023_0101'),
    ]

    operations = [
        migrations.RunPython(set_people),
    ]
