# Generated by Django 4.1.10 on 2024-07-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0006_taxonomy_is_alias_alter_event_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_with_taxonomy_slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='type',
            field=models.CharField(choices=[('vulnerability', 'Vulnerability'), ('incident', 'Incident'), ('other', 'Other')], max_length=20),
        ),
    ]
