# Generated by Django 4.1.10 on 2024-08-08 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ngen', '0007_taxonomy_needs_review_taxonomygroup_needs_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('affected', 'Affected'), ('reporter', 'Reporter'), ('intern', 'Intern')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('root_message_id', models.CharField(max_length=255)),
                ('parent_message_id', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'email_message',
            },
        ),
        migrations.CreateModel(
            name='CommunicationChannelTypeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('communication_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channel_type_relations', to='ngen.communicationchannel')),
                ('communication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channel_type_relations', to='ngen.communicationtype')),
            ],
            options={
                'unique_together': {('communication_channel', 'communication_type')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationChannelContactRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('communication_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channel_contact_relations', to='ngen.communicationchannel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channel_contact_relations', to='ngen.contact')),
            ],
            options={
                'unique_together': {('communication_channel', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='additional_contacts',
            field=models.ManyToManyField(through='ngen.CommunicationChannelContactRelation', to='ngen.contact'),
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='communication_types',
            field=models.ManyToManyField(through='ngen.CommunicationChannelTypeRelation', to='ngen.communicationtype'),
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
