# Generated by Django 3.2.5 on 2021-12-09 22:28

from django.db import migrations


def copy_taxonomy_values_to_types(apps, schema_editor):
    taxonomy_values = apps.get_model('ngen', 'TaxonomyValue')
    incident_types = apps.get_model('ngen', 'IncidentType')

    for taxonomy_value in taxonomy_values.objects.all():
        try:
            incident_type = incident_types.objects.get(slug=taxonomy_value.slug)
            incident_type.description = taxonomy_value.description
            incident_type.name = taxonomy_value.expanded
            incident_type.parent = incident_types.objects.get(slug=taxonomy_value.taxonomypredicate.slug)
            incident_type.save()
        except:
            incident_types.objects.create(name=taxonomy_value.expanded,
                                          description=taxonomy_value.description,
                                          slug=taxonomy_value.slug,
                                          parent=incident_types.objects.get(slug=taxonomy_value.taxonomypredicate.slug)
                                          )


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0007_auto_20211209_2320'),
    ]

    operations = [
        migrations.RunPython(
            code=copy_taxonomy_values_to_types,
        ),
    ]
