# Generated by Django 3.2.5 on 2021-10-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0007_merge_ip_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='network',
            name='ip_mask',
        ),
    ]
