# Generated by Django 4.2.7 on 2024-08-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0008_communicationchannel_communicationtype_emailmessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='recipient',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='recipients',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='references',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='send_attempt_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='senders',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='parent_message_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
