# Generated by Django 3.2.5 on 2021-11-05 19:44
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0008_auto_20211023_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['cidr']},
        ),
    ]
