# Generated by Django 4.2.15 on 2024-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0008_communicationchannel_communicationtype_emailmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissionSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_dashboard', 'View Dashboard'), ('view_minified_feed', 'View Minified Feed'), ('view_minified_tlp', 'View Minified TLP'), ('view_minified_priority', 'View Minified Priority'), ('view_minified_artifact', 'View Minified Artifact'), ('view_minified_user', 'View Minified User'), ('view_minified_case', 'View Minified Case'), ('view_minified_entity', 'View Minified Entity'), ('view_minified_contact', 'View Minified Contact'), ('view_minified_state', 'View Minified State'), ('view_minified_taxonomy', 'View Minified Taxonomy'), ('view_minified_taxonomygroup', 'View Minified TaxonomyGroup'), ('view_userprofile', 'View UserProfile'), ('change_userprofile', 'Change UserProfile'), ('view_stringidentifier', 'View StringIdentifier'), ('use_stringidentifier', 'Use StringIdentifier')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
