# Generated by Django 4.2.7 on 2024-10-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0009_rename_recipient_emailmessage_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationchannel',
            name='additional_contacts',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='recipients',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='senders',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CommunicationChannelContactRelation',
        ),
        migrations.AddField(
            model_name='communicationchannel',
            name='additional_contacts',
            field=models.JSONField(default=list),
        ),
    ]
