# Generated by Django 3.2.5 on 2021-11-10 15:26

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0009_alter_network_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cidr',
            field=netfields.fields.CidrAddressField(max_length=43, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='domain',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=netfields.fields.CidrAddressField(max_length=43, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='cidr',
            field=netfields.fields.CidrAddressField(max_length=43, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='domain',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
