# Generated by Django 4.2.7 on 2024-10-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0010_remove_communicationchannel_additional_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='template',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
