# Generated by Django 3.2.5 on 2021-11-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0010_auto_20211110_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='domain',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='domain',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
