# Generated by Django 4.2.15 on 2024-09-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0010_contact_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('view_case_network_admin', 'Can view case as network admin'), ('add_case_network_admin', 'Can add case as network admin'), ('change_case_network_admin', 'Can change case as network admin'), ('delete_case_network_admin', 'Can delete case as network admin')]},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['username'], 'permissions': [('view_contact_network_admin', 'Can view contact as network admin'), ('add_contact_network_admin', 'Can add contact as network admin'), ('change_contact_network_admin', 'Can change contact as network admin'), ('delete_contact_network_admin', 'Can delete contact as network admin')]},
        ),
        migrations.AlterModelOptions(
            name='custompermissionsupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_dashboard', 'View Dashboard'), ('view_minified_feed', 'View Minified Feed'), ('view_minified_tlp', 'View Minified TLP'), ('view_minified_priority', 'View Minified Priority'), ('view_minified_artifact', 'View Minified Artifact'), ('view_minified_user', 'View Minified User'), ('view_minified_case', 'View Minified Case'), ('view_minified_entity', 'View Minified Entity'), ('view_minified_contact', 'View Minified Contact'), ('view_minified_state', 'View Minified State'), ('view_minified_taxonomy', 'View Minified Taxonomy'), ('view_minified_taxonomygroup', 'View Minified TaxonomyGroup'), ('view_userprofile', 'View UserProfile'), ('change_userprofile', 'Change UserProfile'), ('view_stringidentifier', 'View StringIdentifier'), ('use_stringidentifier', 'Use StringIdentifier'), ('view_dashboard_network_admin', 'View Dashboard as network admin'))},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'permissions': [('view_event_network_admin', 'Can view event as network admin'), ('add_event_network_admin', 'Can add event as network admin'), ('change_event_network_admin', 'Can change event as network admin'), ('delete_event_network_admin', 'Can delete event as network admin')]},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'permissions': [('view_evidence_network_admin', 'Can view evidence as network admin'), ('add_evidence_network_admin', 'Can add evidence as network admin'), ('change_evidence_network_admin', 'Can change evidence as network admin'), ('delete_evidence_network_admin', 'Can delete evidence as network admin')]},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-cidr'], 'permissions': [('view_network_network_admin', 'Can view network as network admin'), ('add_network_network_admin', 'Can add network as network admin'), ('change_network_network_admin', 'Can change network as network admin'), ('delete_network_network_admin', 'Can delete network as network admin')]},
        ),
        migrations.AlterModelOptions(
            name='networkentity',
            options={'permissions': [('view_networkentity_network_admin', 'Can view network entity as network admin'), ('add_networkentity_network_admin', 'Can add network entity as network admin'), ('change_networkentity_network_admin', 'Can change network entity as network admin'), ('delete_networkentity_network_admin', 'Can delete network entity as network admin')]},
        ),
    ]
