# Generated by Django 3.2.5 on 2021-12-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0010_auto_20211209_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentType',
            new_name='Taxonomy',
        ),
        migrations.AlterModelTable(
            name='taxonomy',
            table='taxonomy',
        ),
    ]
