# Generated by Django 4.2.7 on 2024-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0011_emailmessage_template_alter_emailmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='template_params',
            field=models.JSONField(null=True),
        ),
    ]
