# Generated by Django 3.2.5 on 2021-11-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0011_auto_20211119_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.network'),
        ),
    ]
