# Generated by Django 4.2.16 on 2024-11-28 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0012_alter_custompermissionsupport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contact_info', models.CharField(blank=True, help_text="Contact info of the contact if it's not a contact or an user", max_length=255, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngen.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solved_mark',
            },
        ),
    ]
