# Generated by Django 3.2.5 on 2021-12-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0012_taxonomy_auto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='type',
            new_name='taxonomy',
        ),
        migrations.RenameField(
            model_name='incidentdecision',
            old_name='type',
            new_name='taxonomy',
        ),
        migrations.RenameField(
            model_name='incidentdetected',
            old_name='type',
            new_name='taxonomy',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='type',
            new_name='taxonomy',
        ),
        migrations.AddField(
            model_name='incident',
            name='taxonomy_fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidentdecision',
            name='taxonomy_fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidentdetected',
            name='taxonomy_fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='taxonomy_fake_id',
            field=models.IntegerField(null=True),
        ),
    ]
