# Generated by Django 3.2.5 on 2021-11-26 14:47

from django.db import migrations


def set_cidr(apps, schema_editor):
    hosts = apps.get_model('ngen', 'Host')
    for row in hosts.objects.all():
        if row.ip:
            row.cidr = row.ip
            row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0012_network_parent'),
    ]

    operations = [
        migrations.RunPython(set_cidr)
    ]
