# Generated by Django 4.2.16 on 2024-10-25 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0013_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mapping_from', models.CharField(max_length=255)),
                ('mapping_to', models.CharField(max_length=255)),
                ('analyzer_type', models.CharField(max_length=255)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='ngen.taxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
