# Generated by Django 3.2.5 on 2021-11-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0013_rename_ip_host_cidr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ip',
        ),
    ]
