# Generated by Django 3.2.5 on 2021-12-10 15:17

from django.db import migrations


def update_taxonomy_relations(apps, schema_editor):
    update_taxonomy_fake_id(apps.get_model('ngen', 'IncidentReport').objects.all())
    update_taxonomy_fake_id(apps.get_model('ngen', 'IncidentDecision').objects.all())
    update_taxonomy_fake_id(apps.get_model('ngen', 'IncidentDetected').objects.all())
    update_taxonomy_fake_id(apps.get_model('ngen', 'Incident').objects.all())


def update_taxonomy_fake_id(relations):
    for related in relations:
        related.taxonomy_fake_id = related.taxonomy.auto_id
        related.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0013_auto_20211210_1517'),
    ]

    operations = [
        migrations.RunPython(
            code=update_taxonomy_relations,
        ),
    ]
