# Generated by Django 4.2.16 on 2024-10-24 11:50

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ngen', '0013_case_tags_event_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='ngen.ngentag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='ngen.TaggedObject', to='ngen.NgenTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='ngen.TaggedObject', to='ngen.NgenTag', verbose_name='Tags'),
        ),
    ]
