# Generated by Django 3.2.5 on 2021-12-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0014_auto_20211210_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='incidentdecision',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='incidentdetected',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='taxonomy',
        ),
    ]
