# Generated by Django 3.2.5 on 2021-11-26 15:05

from django.db import migrations


def set_cidr(apps, schema_editor):
    hosts = apps.get_model('ngen', 'Host')
    networks = apps.get_model('ngen', 'Host')
    for host in hosts.objects.all():
        if host.domain:
            networks.objects.get_or_create(domain=host.address.address)
        elif host.cidr:
            networks.objects.get_or_create(cidr=host.address.address)


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0014_remove_host_ip'),
    ]

    operations = [
        migrations.RunPython(set_cidr)
    ]
