# Generated by Django 3.2.5 on 2021-11-26 15:05

from django.db import migrations

from ngen.models import Network, Host


def set_cidr(apps, schema_editor):
    # hosts = apps.get_model('ngen', 'Host')
    # networks = apps.get_model('ngen', 'Host')
    net = None
    for host in Host.objects.all():
        if host.guess_address_type(host.address.address) == host.DOMAIN_ADDRESS:
            Network.objects.get_or_create(domain=host.address.address)
        elif host.guess_address_type(host.address.address) in [host.IPV4_ADDRESS, host.IPV6_ADDRESS]:
            Network.objects.get_or_create(cidr=host.address.address)


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0014_remove_host_ip'),
    ]

    operations = [
        migrations.RunPython(set_cidr)
    ]
