# Generated by Django 4.2.16 on 2024-10-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0014_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='taxonomy',
        ),
        migrations.AlterField(
            model_name='mapping',
            name='mapping_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='ngen.taxonomy'),
        ),
    ]
