# Generated by Django 4.2.17 on 2024-12-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0015_solvedmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'permissions': [('view_event_network_admin', 'Can view event as network admin'), ('add_event_network_admin', 'Can add event as network admin'), ('change_event_network_admin', 'Can change event as network admin'), ('delete_event_network_admin', 'Can delete event as network admin'), ('can_mark_event_as_solved', 'Can mark an event as solved'), ('can_retest_event', 'Can retest an event')]},
        ),
    ]
