# Generated by Django 3.2.5 on 2021-12-10 15:43

from django.db import migrations, models


def add_parent_auto_id(apps, schema_editor):
    taxonomies = apps.get_model('ngen', 'Taxonomy')
    for n, taxonomy in enumerate(taxonomies.objects.all()):
        if taxonomy.parent:
            taxonomy.parent_auto_id = taxonomy.parent.auto_id
            taxonomy.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0015_auto_20211210_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='parent_auto_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(
            code=add_parent_auto_id,
        ),
    ]
