# Generated by Django 4.2.16 on 2024-10-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0015_remove_mapping_taxonomy_alter_mapping_mapping_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='kintun_id',
            new_name='analyzer_url',
        ),
    ]
