# Generated by Django 4.2.7 on 2024-11-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0012_alter_custompermissionsupport_options_and_more'),
        ('ngen', '0015_emailmessage_attachments'),
    ]

    operations = [
    ]
