# Generated by Django 4.2.17 on 2024-12-10 14:29

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0016_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ngen.TaggedObject', to='ngen.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ngen.TaggedObject', to='ngen.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedobject',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='ngen.tag'),
        ),
    ]
