# Generated by Django 3.2.5 on 2021-12-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0016_taxonomy_parent_auto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='parent',
        ),
    ]
