# Generated by Django 4.2.16 on 2024-10-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0016_rename_kintun_id_analysis_analyzer_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapping',
            new_name='AnalyzerMapping',
        ),
        migrations.RenameModel(
            old_name='Analysis',
            new_name='EventAnalysis',
        ),
        migrations.AlterModelTable(
            name='analyzermapping',
            table='analyzer_mapping',
        ),
        migrations.AlterModelTable(
            name='eventanalysis',
            table='event_analysis',
        ),
    ]
