# Generated by Django 3.2.5 on 2021-11-26 15:05

from django.db import migrations

from ngen.models import Network, Incident


def incident_origin_to_network(apps, schema_editor):
    incidents = Incident.objects.all()
    network = None
    for incident in incidents:
        if incident.origin.domain:
            network = Network.objects.get(domain=incident.origin.address.address)
        elif incident.origin.cidr:
            network = Network.objects.get(cidr=incident.origin.address.address)
        incident.network = network
        incident.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0016_network_parent_default'),
    ]

    operations = [
        migrations.RunPython(incident_origin_to_network)
    ]
