# Generated by Django 4.2.17 on 2024-12-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0016_merge_20241118_2129'),
        ('ngen', '0017_alter_case_tags_alter_event_tags_and_more'),
    ]

    operations = [
    ]
