# Generated by Django 3.2.5 on 2021-11-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0017_incident_origin_to_network'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtTranslations',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='network',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='network',
            name='country_code',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
