# Generated by Django 3.2.5 on 2021-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0018_auto_20211210_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='auto_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
