# Generated by Django 4.2.17 on 2025-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0018_merge_20241217_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(null=True),
        ),
    ]
