# Generated by Django 3.2.5 on 2021-11-29 22:06

from django.db import migrations


def delete_rdap_networks(apps, schema_editor):
    rdap = apps.get_model('ngen', 'Network').objects.filter(type='rdap').filter(incident__isnull=True)
    rdap.update(parent=None)
    apps.get_model('ngen', 'Network').objects.filter(parent_id__in=rdap).update(parent=None)
    rdap.delete()
    apps.get_model('ngen', 'Network').objects.filter(parent__isnull=True).exclude(cidr='0.0.0.0/0').update(
        parent=apps.get_model('ngen', 'Network').objects.get(cidr='0.0.0.0/0'))


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0019_alter_network_options'),
    ]

    operations = [
        migrations.RunPython(delete_rdap_networks)
    ]
