# Generated by Django 4.2.17 on 2025-02-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0019_emailmessage_body_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='template_params',
        ),
    ]
