# Generated by Django 3.2.5 on 2021-12-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0020_delete_rdap_networks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-cidr']},
        ),
        migrations.RemoveField(
            model_name='network',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='networkadmin',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='networkentity',
            name='is_removed',
        ),
    ]
