# Generated by Django 3.2.5 on 2021-12-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0020_rename_auto_id_taxonomy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='parent_auto_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.taxonomy'),
        ),
    ]
