# Generated by Django 4.2.20 on 2025-08-11 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0020_remove_emailmessage_template_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(blank=True, help_text='If the contact confirmed that their information is up-to-date.', null=True)),
                ('is_lastone', models.BooleanField(default=True, help_text='If the ContactCheck is the last one.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='ngen.contact')),
            ],
            options={
                'verbose_name': 'Contact Verification',
                'verbose_name_plural': 'Contact Verifications',
                'db_table': 'contact_check',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='last_check',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_contact', to='ngen.contactcheck'),
        ),
    ]
