# Generated by Django 3.2.5 on 2021-11-29 22:06

from django.db import migrations


def priority_repited_deletion(apps, schema_editor):
    update_priority(apps.get_model('ngen', 'Incident'))
    update_priority(apps.get_model('ngen', 'IncidentDetected'))
    update_priority(apps.get_model('ngen', 'IncidentDecision'))
    apps.get_model('ngen', 'IncidentPriority').objects.get(pk=7).delete()
    apps.get_model('ngen', 'IncidentPriority').objects.get(pk=9).delete()
    apps.get_model('ngen', 'IncidentPriority').objects.get(pk=4).delete()
    apps.get_model('ngen', 'IncidentPriority').objects.get(pk=8).delete()


def update_priority(manager):
    manager.objects.filter(priority=7).update(priority=3)
    manager.objects.filter(priority=9).update(priority=2)
    manager.objects.filter(priority=4).update(priority=2)
    manager.objects.filter(priority=8).update(priority=6)


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0021_auto_20211203_2043'),
    ]

    operations = [
        migrations.RunPython(priority_repited_deletion)
    ]
