# Generated by Django 4.2.25 on 2026-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0021_contactcheck_contact_last_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avoid_auto_merge',
            field=models.BooleanField(default=False),
        ),
    ]
