# Generated by Django 4.2.25 on 2026-02-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ngen', '0023_alter_casetemplate_case_tlp_and_more'), ('ngen', '0024_alter_casetemplate_priority'), ('ngen', '0025_remove_casetemplate_priority_and_more')]

    dependencies = [
        ('ngen', '0022_event_avoid_auto_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetemplate',
            name='case_tlp',
            field=models.ForeignKey(blank=True, help_text='TLP of the cases created with this template. If not set, it will be the same as the first event that triggered the case creation or TLP default if there is no events.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ngen.tlp'),
        ),
        migrations.AlterField(
            model_name='event',
            name='avoid_auto_merge',
            field=models.BooleanField(default=False, help_text='If true, this event will not be automatically merged with other events even if they have the same taxonomy, feed, cidr and domain. Can be merged manually with any event.'),
        ),
        migrations.RemoveField(
            model_name='casetemplate',
            name='priority',
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='case_priority',
            field=models.ForeignKey(blank=True, help_text='Priority of the cases created with this template. If not set, it will be the same as the first event that triggered the case creation or priority default if there is no events.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ngen.priority'),
        ),
    ]
