# Generated by Django 3.2.5 on 2021-12-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0022_rename_parent_auto_id_taxonomy_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='taxonomy_fake_id',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='incidentdecision',
            name='taxonomy_fake_id',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='incidentdetected',
            name='taxonomy_fake_id',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='taxonomy_fake_id',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.taxonomy'),
        ),
    ]
