# Generated by Django 3.2.5 on 2021-12-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0023_auto_20211204_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='discr',
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.incidentpriority'),
        ),
    ]
