# Generated by Django 3.2.5 on 2021-12-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0025_contact_change_case_for_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_case',
        ),
        migrations.RemoveField(
            model_name='stateedge',
            name='mail_admin',
        ),
        migrations.RemoveField(
            model_name='stateedge',
            name='mail_assigned',
        ),
        migrations.RemoveField(
            model_name='stateedge',
            name='mail_reporter',
        ),
        migrations.RemoveField(
            model_name='stateedge',
            name='mail_team',
        ),
        migrations.DeleteModel(
            name='ContactCase',
        ),
    ]
