# Generated by Django 3.2.5 on 2021-12-10 17:33

from django.db import migrations, models


def add_report_auto_id(apps, schema_editor):
    reports = apps.get_model('ngen', 'IncidentReport')
    for n, report in enumerate(reports.objects.all()):
        report.fake_id = n
        report.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0026_alter_taxonomy_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(
            code=add_report_auto_id,
        ),
    ]
