# Generated by Django 3.2.5 on 2021-12-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0026_auto_20211204_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='networkadmin',
            name='active',
        ),
        migrations.RemoveField(
            model_name='networkadmin',
            name='slug',
        ),
        migrations.AlterField(
            model_name='contact',
            name='network_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ngen.networkadmin'),
        ),
    ]
