# Generated by Django 4.2.26 on 2026-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0027_analyzermapping_add_analyzer_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='was_auto_closed',
            field=models.BooleanField(default=False),
        ),
    ]
