# Generated by Django 3.2.5 on 2021-11-29 22:06

from django.db import migrations


def delete_network_null_relation(apps, schema_editor):
    apps.get_model('ngen', 'NetworkAdmin').objects.filter(network__isnull=True).delete()
    apps.get_model('ngen', 'NetworkEntity').objects.filter(network__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0027_auto_20211205_0104'),
    ]

    operations = [
        migrations.RunPython(delete_network_null_relation)
    ]
