# Generated by Django 3.2.5 on 2021-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0027_incidentreport_fake_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='slug',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='fake_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),

    ]
