# Generated by Django 3.2.5 on 2021-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0028_delete_network_null_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='encryption_key',
            new_name='public_key',
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('technical', 'technical'), ('administrative', 'administrative'), ('abuse', 'abuse'), ('notifications', 'notifications'), ('noc', 'noc')], default='administrative', max_length=20),
        ),
        migrations.AddField(
            model_name='network',
            name='contacts',
            field=models.ManyToManyField(to='ngen.Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('email', 'email'), ('telegram', 'telegram'), ('phone', 'phone')], default='email', max_length=20),
        ),
    ]
