# Generated by Django 3.2.5 on 2021-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0028_auto_20211210_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='fake_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
    ]
