# Generated by Django 4.2.26 on 2026-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0029_emailmessage_retried'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of Celery retry attempts for this email'),
        ),
    ]
