# Generated by Django 3.2.5 on 2021-11-29 22:06

from django.db import migrations


def admin_to_contacts(apps, schema_editor):
    for network in apps.get_model('ngen', 'Network').objects.all():
        if network.network_admin:
            network.network_admin.contact_set.update(name=network.network_admin.name)
            network.contacts.set(network.network_admin.contact_set.all())
            network.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0029_auto_20211205_1420'),
    ]

    operations = [
        migrations.RunPython(admin_to_contacts)
    ]
