# Generated by Django 3.2.5 on 2021-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0029_auto_20211210_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='fake_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
