# Generated by Django 4.2.26 on 2026-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0030_emailmessage_retry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='dispatched',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='send_attempt_failed',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sent',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('sending', 'Sending'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('sent', 'Sent')], db_index=True, default='pending', max_length=16),
        ),
    ]
