# Generated by Django 3.2.5 on 2021-12-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0030_auto_20211210_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentReport',
            new_name='Report',
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
