# Generated by Django 3.2.5 on 2021-12-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0030_admin_to_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='network_admin',
        ),
        migrations.RemoveField(
            model_name='network',
            name='network_admin',
        ),
        migrations.DeleteModel(
            name='NetworkAdmin',
        ),
    ]
