# Generated by Django 3.2.5 on 2021-12-05 15:50

from django.db import migrations, models
from django.db.models import Count


def remove_duplicates(apps, schema_editor):
    duplicates = apps.get_model('ngen', 'Contact').objects.values('username').annotate(
        email_count=Count('username')).filter(email_count__gt=1)
    for data in duplicates:
        contact_duplicate = apps.get_model('ngen', 'Contact').objects.filter(username=data['username']).order_by(
            'pk')
        for duplicate in contact_duplicate[1:]:
            contact_duplicate.first().network_set.add(*duplicate.network_set.all())
            duplicate.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0031_auto_20211205_1521'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunPython(remove_duplicates),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
