# Generated by Django 3.2.5 on 2021-12-10 17:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0031_auto_20211210_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='deletedat',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
