# Generated by Django 3.2.5 on 2021-12-06 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0033_auto_20211205_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentPriority',
            new_name='Priority',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated_at',
            new_name='modified',
        ),
    ]
