# Generated by Django 3.2.5 on 2021-12-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0033_auto_20211210_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='active',
        ),
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
        migrations.AlterField(
            model_name='report',
            name='derivated_problem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='more_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='recomendations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='report',
            name='verification',
            field=models.TextField(null=True),
        ),
    ]
