# Generated by Django 3.2.5 on 2021-12-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0034_auto_20211210_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('lang', 'taxonomy')},
        ),
    ]
