# Generated by Django 4.2.26 on 2026-08-01 11:21

from django.db import migrations, models


def set_order_from_current_ordering(apps, schema_editor):
    """
    Give every task the position it already had, so that upgrading does not
    reorder any playbook: until now the tasks were sorted by the severity of
    their priority, with no defined order between the ones sharing it.
    """
    Playbook = apps.get_model("ngen", "Playbook")
    Task = apps.get_model("ngen", "Task")

    for playbook in Playbook.objects.all():
        tasks = Task.objects.filter(playbook=playbook).order_by(
            "priority__severity", "id"
        )
        for position, task in enumerate(tasks, start=1):
            task.order = position
        Task.objects.bulk_update(tasks, ["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("ngen", "0036_playbook_optional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Position of the task within its playbook. A playbook is a procedure, so its tasks are followed in this order and not by priority.",
            ),
        ),
        migrations.RunPython(
            set_order_from_current_ordering, migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="todotask",
            options={"ordering": ["task__playbook", "task__order", "task_id"]},
        ),
    ]
