# Generated by Django 4.0 on 2021-12-24 16:13
import django.db.models.deletion
from django.db import migrations, models


def add_state_auto_id(apps, schema_editor):
    states = apps.get_model('ngen', 'IncidentState')
    for n, state in enumerate(states.objects.all()):
        state.fake_id = n + 1
        state.save()


def add_behavior_auto_id(apps, schema_editor):
    behaviors = apps.get_model('ngen', 'StateBehavior')
    for n, behavior in enumerate(behaviors.objects.all()):
        behavior.fake_id = n + 1
        behavior.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0037_rename_derivated_problem_report_derived_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstate',
            name='fake_behavior',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidentstate',
            name='fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statebehavior',
            name='fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stateedge',
            name='child',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stateedge',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.networkentity'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.RunPython(
            code=add_behavior_auto_id,
        ),
        migrations.RunPython(
            code=add_state_auto_id,
        ),
    ]
