# Generated by Django 4.2.30 on 2026-08-07 11:18

import random
import re

from django.db import migrations, models

PLACEHOLDER_DOMAIN = "@ngen.invalid"


def _free_email(candidate, taken):
    """
    A variation of the email that no other user has, keeping its domain
    """
    local, _, domain = candidate.partition("@")
    while candidate in taken:
        candidate = f"{local}{random.randint(1000, 9999)}@{domain}"
    taken.add(candidate)
    return candidate


def _placeholder_email(user):
    """
    Something valid and recognizable for a user that has no email at all, so
    that an administrator can find it and replace it with the real one
    """
    local = re.sub(r"[^A-Za-z0-9._-]", "", user.username) or f"user{user.pk}"
    return f"{local}{PLACEHOLDER_DOMAIN}"


def make_emails_unique(apps, schema_editor):
    """
    The email becomes the identity of the user, so every account needs one and
    no two accounts can share it. The oldest account keeps the address and the
    others get a numbered variation of it, which an administrator then fixes
    from the users page.
    """
    User = apps.get_model("ngen", "User")

    taken = set()
    for user in User.objects.order_by("pk").iterator():
        email = (user.email or "").strip().lower()
        if not email:
            email = _placeholder_email(user)

        unique_email = _free_email(email, taken)
        if unique_email != user.email:
            User.objects.filter(pk=user.pk).update(email=unique_email)


def noop(apps, schema_editor):
    """
    Nothing to undo: the rewritten emails are the only ones left and the
    original duplicates cannot be told apart anymore
    """


class Migration(migrations.Migration):

    dependencies = [
        ("ngen", "0037_task_order"),
    ]

    operations = [
        migrations.RunPython(make_emails_unique, noop),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
