# Generated by Django 4.0 on 2021-12-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0038_incidentstate_fake_behavior_incidentstate_fake_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='public_key',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='networkentity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='networkentity',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
