# Generated by Django 4.0 on 2021-12-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0040_auto_20211224_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateedge',
            name='newstate',
            field=models.ForeignKey(blank=True, db_column='newState', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='newstate', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='oldstate',
            field=models.ForeignKey(blank=True, db_column='oldState', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oldstate', to='ngen.incidentstate'),
        ),
    ]
