# Generated by Django 4.0 on 2021-12-24 18:25

from django.db import migrations


def add_incident_fake_id(apps, schema_editor):
    incidents = apps.get_model('ngen', 'Incident')
    for incident in incidents.objects.all():
        incident.fake_state = incident.state.fake_id
        incident.fake_unsolved_state = incident.unsolved_state.fake_id
        incident.fake_unresponded_state = incident.unresponded_state.fake_id
        incident.save()


def add_incident_decision_fake_id(apps, schema_editor):
    decisions = apps.get_model('ngen', 'IncidentDecision')
    for decision in decisions.objects.all():
        decision.fake_state = decision.state.fake_id
        decision.fake_unsolved_state = decision.unsolved_state.fake_id
        decision.fake_unresponded_state = decision.unresponded_state.fake_id
        decision.save()


def add_incident_detected_fake_id(apps, schema_editor):
    decisions = apps.get_model('ngen', 'IncidentDetected')
    for decision in decisions.objects.all():
        decision.fake_state = decision.state.fake_id
        decision.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0043_incident_fake_state_incident_fake_unresponded_state_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=add_incident_fake_id,
        ),
        migrations.RunPython(
            code=add_incident_detected_fake_id,
        ),
        migrations.RunPython(
            code=add_incident_decision_fake_id,
        )
    ]
