# Generated by Django 4.0 on 2021-12-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0044_auto_20211224_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='state',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='unresponded_state',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='unsolved_state',
        ),
        migrations.RemoveField(
            model_name='incidentdecision',
            name='state',
        ),
        migrations.RemoveField(
            model_name='incidentdecision',
            name='unresponded_state',
        ),
        migrations.RemoveField(
            model_name='incidentdecision',
            name='unsolved_state',
        ),
        migrations.RemoveField(
            model_name='incidentdetected',
            name='state',
        ),
        migrations.RemoveField(
            model_name='incidentstate',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='stateedge',
            name='newstate',
        ),
        migrations.RemoveField(
            model_name='stateedge',
            name='oldstate',
        ),
    ]
