# Generated by Django 4.0 on 2021-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0045_remove_incident_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstate',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='slug',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='fake_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='fake_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
