# Generated by Django 4.0 on 2021-12-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0046_alter_incidentstate_fake_id_alter_incidentstate_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstate',
            name='fake_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='fake_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
