# Generated by Django 4.0 on 2021-12-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0047_alter_incidentstate_fake_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentstate',
            old_name='fake_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='statebehavior',
            old_name='fake_id',
            new_name='id',
        ),
    ]
