# Generated by Django 4.0 on 2021-12-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0048_rename_fake_id_incidentstate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='fake_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='fake_unresponded_state',
            new_name='unresponded_state',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='fake_unsolved_state',
            new_name='unsolved_state',
        ),
        migrations.RenameField(
            model_name='incidentdecision',
            old_name='fake_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='incidentdecision',
            old_name='fake_unresponded_state',
            new_name='unresponded_state',
        ),
        migrations.RenameField(
            model_name='incidentdecision',
            old_name='fake_unsolved_state',
            new_name='unsolved_state',
        ),
        migrations.RenameField(
            model_name='incidentdetected',
            old_name='fake_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='incidentstate',
            old_name='fake_behavior',
            new_name='behavior',
        ),
    ]
