# Generated by Django 4.0 on 2021-12-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0049_rename_fake_state_incident_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incident_states', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='unresponded_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incident_unresponded_states', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='unsolved_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incident_unsolved_states', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='incidentdecision',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_states', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='incidentdecision',
            name='unresponded_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_unresponded_states', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='incidentdecision',
            name='unsolved_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_unsolved_states', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='incidentdetected',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.incidentstate'),
        ),
    ]
