# Generated by Django 4.0 on 2021-12-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0050_alter_incident_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstate',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.statebehavior'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='ngen.incidentstate'),
        ),
    ]
