# Generated by Django 4.0 on 2021-12-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0051_alter_incidentstate_behavior_alter_stateedge_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateedge',
            name='deletedat',
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='deletedat',
            field=models.DateTimeField(db_column='deletedAt', null=True),
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='deletedat',
            field=models.DateTimeField(db_column='deletedAt', null=True),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='incident_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='state_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.stateedge'),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='deletedat',
            field=models.DateTimeField(db_column='deletedAt', null=True),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
