# Generated by Django 4.0 on 2021-12-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0052_remove_stateedge_deletedat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentstatechange',
            old_name='responsable',
            new_name='responsible',
        ),
        migrations.RenameField(
            model_name='statebehavior',
            old_name='can_comunicate',
            new_name='can_communicate',
        ),
        migrations.RemoveField(
            model_name='incidentstate',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='incidentstatechange',
            name='deletedat',
        ),
        migrations.RemoveField(
            model_name='statebehavior',
            name='deletedat',
        ),
    ]
