# Generated by Django 4.0 on 2021-12-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0054_alter_incidentstate_id_alter_incidentstatechange_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
