# Generated by Django 4.0 on 2021-12-24 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0056_alter_contact_id_alter_network_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentstate',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='incidentstate',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='incidentstatechange',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='incidentstatechange',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='statebehavior',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='statebehavior',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='stateedge',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='stateedge',
            old_name='updated_at',
            new_name='modified',
        ),
    ]
