# Generated by Django 4.0 on 2021-12-24 19:15

import django.utils.timezone
import model_utils.fields
from django.db import migrations


def update_created_modified_state_change(apps, schema_editor):
    edges = apps.get_model('ngen', 'IncidentStateChange')
    for edge in edges.objects.all():
        if edge.created is None:
            edge.created = edge.date
        if edge.modified is None:
            edge.modified = edge.date
        edge.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0057_incidentstate_created_incidentstate_modified_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=update_created_modified_state_change,
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                      verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='incidentstate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                      verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='incidentstatechange',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                      verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                      verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
    ]
