# Generated by Django 4.0 on 2021-12-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0058_alter_incidentstate_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstate',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='statebehavior',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
