# Generated by Django 4.0 on 2021-12-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0060_alter_networkentity_slug_alter_taxonomy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateedge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ngen.incidentstate'),
        ),
    ]
