# Generated by Django 4.0 on 2021-12-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0061_alter_stateedge_child_alter_stateedge_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstate',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='ngen.StateEdge', to='ngen.IncidentState'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents_state', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children_state', to='ngen.incidentstate'),
        ),
    ]
