# Generated by Django 4.0 on 2021-12-24 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0062_incidentstate_children_alter_stateedge_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateedge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents_edge', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children_edge', to='ngen.incidentstate'),
        ),
    ]
