# Generated by Django 4.0 on 2021-12-25 19:31

from django.db import migrations
from django.db.models import F


def delete_redundant_edges(apps, schema_editor):
    edges = apps.get_model('ngen', 'StateEdge')
    changes = apps.get_model('ngen', 'IncidentStateChange')
    redundant = edges.objects.filter(parent=F('child'))
    changes.objects.filter(state_edge__in=redundant).delete()
    redundant.delete()
    edges.objects.exclude(id__in=changes.objects.all().values('state_edge')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0063_alter_stateedge_child_alter_stateedge_parent'),
    ]

    operations = [
        migrations.RunPython(
            code=delete_redundant_edges,
        ),
    ]
