# Generated by Django 4.0 on 2021-12-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0064_auto_20211225_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateedge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_edge', to='ngen.incidentstate'),
        ),
        migrations.AlterField(
            model_name='stateedge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_edge', to='ngen.incidentstate'),
        ),
    ]
