# Generated by Django 4.0 on 2021-12-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0065_alter_stateedge_child_alter_stateedge_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stateedge',
            unique_together={('parent', 'child')},
        ),
    ]
