# Generated by Django 4.0.1 on 2022-01-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0066_alter_stateedge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='type',
            field=models.CharField(choices=[('vulnerability', 'vulnerability'), ('incident', 'incident')], default='vulnerability', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('es', 'es')], default='en', max_length=2),
        ),
    ]
