# Generated by Django 4.0.1 on 2022-01-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0068_rename_incident_case_rename_incidentdetected_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='case',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
