# Generated by Django 4.0.1 on 2022-01-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0069_alter_case_table_alter_event_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentFeed',
            new_name='Feed',
        ),
        migrations.AlterModelTable(
            name='feed',
            table='feed',
        ),
    ]
