# Generated by Django 4.0.1 on 2022-01-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0073_rename_incidentdecision_casetemplate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casetemplate',
            table='case_template',
        ),
    ]
