# Generated by Django 4.0.1 on 2022-01-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0074_alter_casetemplate_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentState',
            new_name='State',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
    ]
