# Generated by Django 4.0.1 on 2022-01-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0075_rename_incidentstate_state_alter_state_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StateEdge',
            new_name='Edge',
        ),
        migrations.AlterModelTable(
            name='edge',
            table='edge',
        ),
    ]
