# Generated by Django 4.0.1 on 2022-01-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0076_rename_stateedge_edge_alter_edge_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StateBehavior',
            new_name='Behavior',
        ),
        migrations.AlterModelTable(
            name='behavior',
            table='behavior',
        ),
    ]
