# Generated by Django 4.0.1 on 2022-01-10 00:21

from django.db import migrations, models


def add_fake_id(objects):
    for n, object in enumerate(objects.objects.all()):
        object.fake_id = n + 1
        object.save()


def add_tlp_fake_id(apps, schema_editor):
    add_fake_id(apps.get_model('ngen', 'Tlp'))


def add_feed_fake_id(apps, schema_editor):
    add_fake_id(apps.get_model('ngen', 'Feed'))


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0078_alter_case_id_alter_casetemplate_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tlp',
            name='fake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(
            code=add_tlp_fake_id,
        ),
        migrations.RunPython(
            code=add_feed_fake_id,
        ),
    ]
