# Generated by Django 4.0.1 on 2022-01-10 14:49

from django.db import migrations, models


def add_fake_relation_id(objects):
    for object in objects.objects.all():
        object.fake_tlp = object.tlp.fake_id
        object.fake_feed = object.feed.fake_id
        object.save()


def add_fake_relation(apps, schema_editor):
    add_fake_relation_id(apps.get_model('ngen', 'Case'))
    add_fake_relation_id(apps.get_model('ngen', 'Event'))
    add_fake_relation_id(apps.get_model('ngen', 'CaseTemplate'))


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0079_feed_fake_id_tlp_fake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fake_feed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='fake_tlp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='fake_feed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='fake_tlp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fake_feed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fake_tlp',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='case',
            old_name='tlp_state',
            new_name='tlp',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tlp_state',
            new_name='tlp',
        ),
        migrations.RunPython(
            code=add_fake_relation,
        ),
    ]
