# Generated by Django 4.0.1 on 2022-01-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0081_alter_case_tlp_alter_casetemplate_tlp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='tlp',
        ),
        migrations.RemoveField(
            model_name='casetemplate',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='casetemplate',
            name='tlp',
        ),
        migrations.RemoveField(
            model_name='event',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tlp',
        ),
    ]
