# Generated by Django 4.0.1 on 2022-01-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0082_remove_case_feed_remove_case_tlp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='fake_feed',
            new_name='feed',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='fake_tlp',
            new_name='tlp',
        ),
        migrations.RenameField(
            model_name='casetemplate',
            old_name='fake_feed',
            new_name='feed',
        ),
        migrations.RenameField(
            model_name='casetemplate',
            old_name='fake_tlp',
            new_name='tlp',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fake_feed',
            new_name='feed',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fake_tlp',
            new_name='tlp',
        ),
    ]
