# Generated by Django 4.0.1 on 2022-01-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0083_rename_fake_feed_case_feed_rename_fake_tlp_case_tlp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tlp',
            name='slug',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='feed',
            name='fake_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tlp',
            name='fake_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),

    ]
