# Generated by Django 4.0.1 on 2022-01-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0084_alter_feed_fake_id_alter_feed_slug_alter_tlp_fake_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='fake_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tlp',
            name='fake_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
