# Generated by Django 4.0.1 on 2022-01-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0085_alter_feed_fake_id_alter_tlp_fake_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='fake_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tlp',
            old_name='fake_id',
            new_name='id',
        ),
    ]
