# Generated by Django 4.0.1 on 2022-01-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0088_alter_case_feed_alter_case_tlp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.feed'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tlp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.tlp'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.feed'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='tlp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.tlp'),
        ),
        migrations.AlterField(
            model_name='event',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.feed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tlp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.tlp'),
        ),
    ]
