# Generated by Django 4.0.1 on 2022-01-10 15:46

import django.db.models.deletion
from django.db import migrations, models


def delete_orphans_events(apps, schema_editor):
    for event in apps.get_model('ngen', 'Event').objects.raw(
            'SELECT * FROM event left join "case" c on event.case = c.id where c.id is null'):
        event.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0091_rename_incident_id_event_case'),
    ]

    operations = [
        migrations.RunPython(
            code=delete_orphans_events,
        ),
        migrations.AlterField(
            model_name='event',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.case'),
        ),
    ]
