# Generated by Django 4.0.1 on 2022-01-10 17:15

from django.db import migrations


def fill_created_updated(apps, schema_editor):
    for event in apps.get_model('ngen', 'Event').objects.all():
        if event.created_at is None or event.updated_at is None:
            event.created_at = event.date
            event.updated_at = event.date
            event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0094_alter_event_created_at_alter_event_priority_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=fill_created_updated,
        ),
    ]
