# Generated by Django 4.0.1 on 2022-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0095_auto_20220110_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
