# Generated by Django 4.0.1 on 2022-01-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0096_alter_event_created_at_alter_event_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetemplate',
            name='auto_saved',
        ),
        migrations.RemoveField(
            model_name='casetemplate',
            name='deletedat',
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.priority'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.taxonomy'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
