# Generated by Django 4.0.1 on 2022-01-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0098_remove_feed_deletedat_alter_feed_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='deletedat',
        ),
        migrations.AlterField(
            model_name='priority',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='priority',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
