# Generated by Django 4.0.1 on 2022-01-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0101_alter_case_created_at_alter_case_evidence_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='casetemplate',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='casetemplate',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='incidentcomment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='tlp',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tlp',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='modified',
        ),
    ]
