# Generated by Django 4.0.1 on 2022-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0103_alter_case_created_alter_case_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tlp',
            name='slug',
            field=models.SlugField(max_length=45),
        ),
    ]
