# Generated by Django 4.0.1 on 2022-01-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0104_alter_feed_slug_alter_tlp_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='evidence_file_path',
        ),
        migrations.RemoveField(
            model_name='case',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='event',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
    ]
