# Generated by Django 4.0.1 on 2022-01-11 18:40

import django.db.models.deletion
from django.db import migrations, models


def add_event_network(apps, schema_editor):
    for event in apps.get_model('ngen', 'Event').objects.all():
        event.network = event.case.network
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0105_remove_case_evidence_file_path_remove_case_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.network'),
        ),
        migrations.RunPython(
            code=add_event_network,
        ),
    ]
