# Generated by Django 4.0.1 on 2022-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0107_remove_message_created_by_alter_behavior_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='network',
        ),
        migrations.RemoveField(
            model_name='case',
            name='reporter',
        ),
        migrations.AlterField(
            model_name='case',
            name='response_dead_line',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='solve_dead_line',
            field=models.DateTimeField(),
        ),
    ]
