# Generated by Django 4.0.1 on 2022-01-11 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0108_remove_case_network_remove_case_reporter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='incident',
            new_name='case',
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases_assigned', to='ngen.user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases', to='ngen.state'),
        ),
        migrations.AlterField(
            model_name='case',
            name='unresponded_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases_unresponded', to='ngen.state'),
        ),
        migrations.AlterField(
            model_name='case',
            name='unsolved_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases_unsolved', to='ngen.state'),
        ),
    ]
