# Generated by Django 4.0.1 on 2022-01-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0109_rename_incident_message_case_alter_case_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ngen.taxonomy'),
        ),
    ]
