# Generated by Django 4.0.1 on 2022-01-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0110_alter_report_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tlp',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
