# Generated by Django 4.0.1 on 2022-01-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0112_alter_case_options_alter_event_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ngen.network'),
        ),
    ]
