# Generated by Django 4.0.1 on 2022-01-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0113_alter_event_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
