# Generated by Django 4.0.1 on 2022-01-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0115_rename_enabled_user_is_active_remove_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_canonical',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_requested_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_canonical',
        ),
    ]
