# Generated by Django 4.0.1 on 2022-02-01 16:12

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0118_user_priority_alter_case_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='report',
            name='derived_problem',
            field=django_bleach.models.BleachField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='more_information',
            field=django_bleach.models.BleachField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='problem',
            field=django_bleach.models.BleachField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='recommendations',
            field=django_bleach.models.BleachField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='verification',
            field=django_bleach.models.BleachField(null=True),
        ),
    ]
