# Generated by Django 4.0.1 on 2022-02-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0120_auto_20220201_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
    ]
