# Generated by Django 4.0.3 on 2022-03-08 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import ngen.models.case
import ngen.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0123_eventevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(null=True, storage=ngen.storage.HashedFilenameStorage(), upload_to=ngen.models.case.Evidence.directory_path)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ngen.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_evidence',
            },
        ),
    ]
