# Generated by Django 4.0.3 on 2022-03-08 21:35

from django.db import migrations, models
import ngen.models.case
import ngen.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0124_caseevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevidence',
            name='file',
            field=models.FileField(null=True, storage=ngen.storage.HashedFilenameStorage(), unique=True, upload_to=ngen.models.case.Evidence.directory_path),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='file',
            field=models.FileField(null=True, storage=ngen.storage.HashedFilenameStorage(), unique=True, upload_to=ngen.models.case.Evidence.directory_path),
        ),
    ]
