# Generated by Django 4.0.3 on 2022-03-15 23:18

from django.db import migrations


def event_merge(apps, schema_editor):
    for case in apps.get_model('ngen', 'Case').objects.all():
        events = list(case.events.all().order_by('id'))
        if len(events) > 1:
            parent = events[:1].pop()
            for event in events[1:]:
                event.parent = parent
                event.case = None
                event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0127_alter_event_parent_alter_network_parent_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=event_merge,
        ),
    ]
