# Generated by Django 4.0.3 on 2022-03-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0130_alter_contact_priority_alter_user_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
