# Generated by Django 4.0.3 on 2022-03-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0131_state_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='behavior',
        ),
        migrations.DeleteModel(
            name='Behavior',
        ),
    ]
