# Generated by Django 4.0.3 on 2022-03-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0132_remove_state_behavior_delete_behavior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='response_time',
            new_name='attend_time',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='unresponse_time',
            new_name='unattended_time',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='unsolve_time',
            new_name='unsolved_time',
        ),
    ]
