# Generated by Django 4.0.3 on 2022-03-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0133_rename_response_time_priority_attend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='active',
        ),
    ]
