# Generated by Django 4.0.3 on 2022-03-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0134_remove_priority_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='unresponded_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases_unattended', to='ngen.state'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='unresponded_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_unattended_states', to='ngen.state'),
        ),
    ]
