# Generated by Django 4.0.3 on 2022-03-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0136_rename_unresponded_state_case_unattended_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='response_dead_line',
            new_name='attend_dead_line',
        ),
    ]
