# Generated by Django 4.0.3 on 2022-03-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0137_rename_response_dead_line_case_attend_dead_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='ltd_count',
        ),
    ]
