# Generated by Django 4.0.3 on 2022-04-03 23:14

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Case = apps.get_model('ngen', 'Case')
    for row in Case.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0138_remove_case_ltd_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid),
    ]
