# Generated by Django 4.0.3 on 2022-04-03 23:18

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Event = apps.get_model('ngen', 'Event')
    for row in Event.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0140_alter_case_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid),
    ]
