# Generated by Django 4.0.3 on 2022-04-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0142_alter_event_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentstatechange',
            old_name='incident_id',
            new_name='case',
        ),
    ]
