# Generated by Django 4.0.3 on 2022-04-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0145_auto_20220404_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatechange',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='ngen.case'),
        ),
    ]
