# Generated by Django 4.0.3 on 2022-04-04 16:46
import json

from auditlog.models import LogEntry
from django.db import migrations


def state_change_to_logentry(apps, schema_editor):
    IncidentStateChange = apps.get_model('ngen', 'IncidentStateChange')
    for state_change in IncidentStateChange.objects.all():
        diff = {'state': (state_change.state_edge.parent.name, state_change.state_edge.child.name)}
        logentry = LogEntry.objects.log_create(state_change.case, action=LogEntry.Action.UPDATE,
                                               changes=json.dumps(diff))
        logentry.timestamp = state_change.created
        logentry.actor_id = state_change.responsible_id
        logentry.object_repr = str(state_change.case.id)
        logentry.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0146_alter_incidentstatechange_case'),
    ]

    operations = [
        migrations.RunPython(state_change_to_logentry),
    ]
