# Generated by Django 4.0.3 on 2022-04-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0147_auto_20220404_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
    ]
