# Generated by Django 4.0.3 on 2022-04-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0148_alter_case_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='case',
            name='attend_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='solve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
