# Generated by Django 4.0.3 on 2022-04-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0149_alter_contact_options_case_attend_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='unattended_time',
            new_name='attend_time_extra',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='unsolved_time',
            new_name='solve_time_extra',
        ),
    ]
