# Generated by Django 4.0.3 on 2022-04-08 23:20

import datetime

from django.db import migrations, models


def time_to_duration(apps, schema_editor):
    Priority = apps.get_model('ngen', 'Priority')
    for priority in Priority.objects.all():
        priority.attend_duration = datetime.timedelta(minutes=priority.attend_time)
        priority.solve_duration = datetime.timedelta(minutes=priority.solve_time)
        priority.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0150_rename_unattended_time_priority_attend_time_extra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='solve_time_extra',
            new_name='attend_deadline',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='attend_time_extra',
            new_name='solve_deadline',
        ),
        migrations.AddField(
            model_name='priority',
            name='attend_duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='priority',
            name='solve_duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.RunPython(time_to_duration),
    ]
