# Generated by Django 4.0.3 on 2022-04-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0151_rename_solve_time_extra_priority_attend_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='attend_time',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='solve_time',
        ),
    ]
