# Generated by Django 4.0.3 on 2022-04-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0153_rename_attend_duration_priority_attend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='attend_deadline',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='solve_deadline',
        ),
    ]
