# Generated by Django 4.0.3 on 2022-04-08 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0154_remove_priority_attend_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='attend_deadline',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='priority',
            name='solve_deadline',
            field=models.DurationField(default=datetime.timedelta(days=2)),
        ),
    ]
