# Generated by Django 4.0.3 on 2022-04-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0156_auto_20220408_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
