# Generated by Django 4.0.3 on 2022-04-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0157_alter_priority_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['severity']},
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='code',
            new_name='severity',
        ),
    ]
