# Generated by Django 4.0.3 on 2022-04-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0158_alter_priority_options_rename_code_priority_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='attend_dead_line',
        ),
        migrations.RemoveField(
            model_name='case',
            name='solve_dead_line',
        ),
        migrations.RemoveField(
            model_name='case',
            name='unattended_state',
        ),
        migrations.RemoveField(
            model_name='case',
            name='unsolved_state',
        ),
    ]
