# Generated by Django 4.0.3 on 2022-04-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0159_remove_case_attend_dead_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='casetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventevidence',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incidentstatechange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='network',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='networkentity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tlp',
            name='created_by',
        ),
    ]
