# Generated by Django 4.0.3 on 2022-04-09 01:30
from django.db import migrations, models

from ngen.models import State


def removed_cases(apps, schema_editor):
    # State = apps.get_model('ngen', 'State')

    removed = State.objects.get(name='Removed')
    if removed:
        for case in removed.cases.all():
            case.delete()
        removed.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0161_auto_20220409_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='case',
            field=models.ForeignKey(null=True, on_delete=models.deletion.DO_NOTHING, related_name='events',
                                    to='ngen.case'),
        ),
        migrations.RunPython(removed_cases)
    ]
