# Generated by Django 4.0.4 on 2022-04-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0165_case_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='lifecycle',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('auto_open', 'Auto open'), ('auto_close', 'Auto close')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('technical', 'Technical'), ('administrative', 'Administrative'), ('abuse', 'Abuse'), ('notifications', 'Notifications'), ('noc', 'NOC')], default='administrative', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('uri', 'URI')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='type',
            field=models.CharField(choices=[('vulnerability', 'Vulnerability'), ('incident', 'Incident')], default='vulnerability', max_length=20),
        ),
    ]
