# Generated by Django 4.0.4 on 2022-04-18 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0166_alter_case_lifecycle_alter_contact_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=60)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Task Lists',
                'db_table': 'task_list',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(null=True)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.priority')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.tasklist')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['priority__severity'],
            },
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(null=True)),
                ('note', models.TextField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.event')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.task')),
            ],
            options={
                'db_table': 'event_task',
                'ordering': ['task__task_list'],
            },
        ),
    ]
