# Generated by Django 4.0.4 on 2022-04-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0167_alter_case_assigned_tasklist_task_eventtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tasks',
            field=models.ManyToManyField(related_name='events', through='ngen.EventTask', to='ngen.task'),
        ),
        migrations.AlterField(
            model_name='eventtask',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tasks', to='ngen.event'),
        ),
        migrations.AlterField(
            model_name='eventtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tasks', to='ngen.task'),
        ),
    ]
