# Generated by Django 4.0.4 on 2022-04-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0169_remove_tasklist_taxonomy_tasklist_taxonomy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventtask',
            unique_together={('task', 'event')},
        ),
    ]
