# Generated by Django 4.0.4 on 2022-04-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0171_todotask_rename_title_task_name_alter_event_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='ngen.event'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='ngen.task'),
        ),
    ]
