# Generated by Django 4.0.4 on 2022-04-19 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0172_alter_todotask_event_alter_todotask_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={},
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=60)),
                ('taxonomy', models.ManyToManyField(related_name='playbooks', to='ngen.taxonomy')),
            ],
            options={
                'db_table': 'playbook',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngen.playbook'),
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
