# Generated by Django 4.0.4 on 2022-04-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0174_rename_task_list_task_playbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['task__playbook']},
        ),
    ]
