# Generated by Django 4.0.4 on 2022-04-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0175_alter_todotask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ngen.playbook'),
        ),
    ]
