# Generated by Django 4.0.4 on 2022-04-26 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import ngen.models.case
import ngen.storage


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ngen', '0176_alter_task_playbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(null=True, storage=ngen.storage.HashedFilenameStorage(), unique=True, upload_to=ngen.models.case.Evidence.directory_path)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='eventevidence',
            name='event',
        ),
        migrations.DeleteModel(
            name='CaseEvidence',
        ),
        migrations.DeleteModel(
            name='EventEvidence',
        ),
    ]
