# Generated by Django 4.0.4 on 2022-04-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0177_evidence_remove_eventevidence_event_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evidence',
            table='evidence',
        ),
    ]
