# Generated by Django 4.0.4 on 2022-04-29 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ngen', '0178_alter_evidence_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('url', 'Url'), ('hash', 'Hash'), ('file', 'File'), ('domain', 'Domain')], default='ip', max_length=20)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='ngen.artifact')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
