# Generated by Django 4.0.4 on 2022-05-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ngen', '0179_artifact_artifactrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_relation', to='contenttypes.contenttype'),
        ),
        migrations.AlterModelTable(
            name='artifact',
            table='artifact',
        ),
        migrations.AlterModelTable(
            name='artifactrelation',
            table='artifact_relation',
        ),
    ]
