# Generated by Django 4.0.4 on 2022-05-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0184_alter_artifactrelation_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('raw', models.JSONField()),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='ngen.artifact')),
            ],
            options={
                'db_table': 'artifact_enrichment',
            },
        ),
    ]
