# Generated by Django 4.0.4 on 2022-05-03 21:56

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0185_artifactenrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactenrichment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='artifactenrichment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactenrichment',
            unique_together={('artifact', 'name')},
        ),
    ]
