# Generated by Django 4.0.4 on 2022-05-06 23:14

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0187_event_cidr_event_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cidr',
            field=netfields.fields.CidrAddressField(max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='domain',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='cidr',
            field=netfields.fields.CidrAddressField(max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='domain',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('cidr', 'domain')},
        ),
    ]
