# Generated by Django 4.0.4 on 2022-05-06 23:15

from django.db import migrations

from ngen.models import Event


def event_address(apps, schema_editor):
    events = Event.objects.all()
    for event in events:
        if event.network.cidr:
            event.cidr = event.network.cidr
        if event.network.domain:
            event.domain = event.network.domain
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0188_alter_event_cidr_alter_event_domain_and_more'),
    ]

    operations = [
        migrations.RunPython(event_address),
    ]
