# Generated by Django 4.0.4 on 2022-05-07 13:53

from django.db import migrations


def delete_auto_networks(apps, schema_editor):
    apps.get_model('ngen', 'Network').objects.filter(type__in=['rdap', 'auto']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0189_auto_20220506_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='network',
        ),
        migrations.RunPython(delete_auto_networks)
    ]
