# Generated by Django 4.0.4 on 2022-05-27 20:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0195_rename_rgb_tlp_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlp',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
