# Generated by Django 4.0.4 on 2022-05-30 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import model_utils.fields
import ngen.communication


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0196_alter_tlp_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('body', django_bleach.models.BleachField(null=True)),
                ('lang', models.CharField(choices=[('en', 'en'), ('es', 'es')], default='en', max_length=2)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.network')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.priority')),
                ('tlp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ngen.tlp')),
            ],
            options={
                'db_table': 'announcement',
            },
            bases=(models.Model, ngen.communication.Communication),
        ),
    ]
