# Generated by Django 4.0.5 on 2022-06-05 00:32

from django.db import migrations


def comments_orphan_delete(apps, schema_editor):
    threads = apps.get_model('ngen', 'IncidentCommentThread')
    Case = apps.get_model('ngen', 'Case')
    for thread in threads.objects.all():
        try:
            Case.objects.get(pk=thread.incident_id)
        except:
            for comment in thread.incidentcomment_set.all():
                comment.delete()
            thread.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0197_announcement'),
    ]

    operations = [
        migrations.RunPython(comments_orphan_delete),
    ]
