# Generated by Django 4.0.5 on 2022-06-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0198_auto_20220605_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentcommentthread',
            old_name='incident_id',
            new_name='case',
        ),
    ]
