# Generated by Django 4.0.5 on 2022-06-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0199_rename_incident_id_incidentcommentthread_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcomment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='ngen.incidentcommentthread'),
        ),
        migrations.AlterField(
            model_name='incidentcommentthread',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='threads', to='ngen.case'),
        ),
    ]
