# Generated by Django 4.0.5 on 2022-06-05 00:52
from comment.models import Comment
from django.db import migrations

from ngen.models import User


def migrate_threads_to_comments(apps, schema_editor):
    threads = apps.get_model('ngen', 'IncidentCommentThread')
    for thread in threads.objects.all():
        for comment in thread.comments.all():
            temp_comment = Comment(
                content_object=thread.case,
                content=comment.body,
                user=User.objects.get(pk=comment.author.pk),
                posted=comment.created
            )
            temp_comment.save()
            thread.case.comments.add(temp_comment)


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0200_alter_incidentcomment_thread_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_threads_to_comments),
    ]
