# Generated by Django 4.0.5 on 2022-06-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0201_auto_20220605_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentcommentthread',
            name='case',
        ),
        migrations.DeleteModel(
            name='IncidentComment',
        ),
        migrations.DeleteModel(
            name='IncidentCommentThread',
        ),
    ]
