# Generated by Django 4.0.5 on 2022-06-05 21:25

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0204_alter_casetemplate_event_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetemplate',
            name='cidr',
            field=netfields.fields.CidrAddressField(max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='domain',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
