# Generated by Django 4.0.5 on 2022-06-05 21:25

from django.db import migrations


def template_network_to_address(apps, schema_editor):
    templates = apps.get_model('ngen', 'CaseTemplate')
    for template in templates.objects.all():
        if template.event_network:
            template.cidr = template.event_network.cidr
            template.domain = template.event_network.domain
            template.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0205_casetemplate_cidr_casetemplate_domain'),
    ]

    operations = [
        migrations.RunPython(template_network_to_address),
    ]
