# Generated by Django 4.0.5 on 2022-06-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0206_auto_20220605_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetemplate',
            name='event_network',
        ),
    ]
