# Generated by Django 4.0.5 on 2022-06-06 00:23

from django.db import migrations


def template_any_network(apps, schema_editor):
    templates = apps.get_model('ngen', 'CaseTemplate')
    for template in templates.objects.filter(cidr__isnull=True, domain__isnull=True):
        default_network = apps.get_model('ngen', 'Network').objects.get(cidr='0.0.0.0/0')
        template.cidr = default_network.cidr
        template.domain = default_network.domain
        template.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ngen', '0207_remove_casetemplate_event_network'),
    ]

    operations = [
        migrations.RunPython(template_any_network),
    ]
