# Generated by Django 4.0.5 on 2022-06-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0208_auto_20220606_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetemplate',
            name='event_count',
        ),
    ]
