# Generated by Django 4.0.8 on 2023-03-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngen', '0209_remove_casetemplate_event_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='attend_deadline',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='solve_deadline',
        ),
        migrations.AlterField(
            model_name='case',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ngen.case'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ngen.event'),
        ),
        migrations.AlterField(
            model_name='network',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ngen.network'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ngen.taxonomy'),
        ),
    ]
