name: Build and Push Docker Images for Release Candidate

on:
  push:
    tags:
      - 'rc-*'  # Se ejecuta solo cuando haces git push de un tag como rc-1.2.3

jobs:
  build-and-push-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag version
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push backend image for ngen-django release candidate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: certunlp/ngen-django:${{ steps.vars.outputs.TAG }}

      - name: Build and push backend image for ngen release candidate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: certunlp/ngen:${{ steps.vars.outputs.TAG }}

      - name: Build and push frontend image release candidate
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: frontend/Dockerfile.prod
          push: true
          tags: certunlp/ngen-frontend:${{ steps.vars.outputs.TAG }}
